tasks:
  - name: Backend Service
    openMode: split-left
    init: |
      sudo apt update
      sudo apt install python3 python3-venv -y
      python3 venv venv
      source ./venv/bin/activate
      cd backend
    command: python -m app.main

  - name: Frontend Service
    openMode: split-right
    init: |
      sudo apt install -y curl
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt install -y nodejs
      cd frontend
    command: npm install & npm run dev

  - name: Grafana
    openMode: tab-after
    init: |
      sudo apt update
      sudo apt install libfontconfig1 musl -y
      wget https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb
      sudo dpkg -i grafana_10.2.3_amd64.deb
    command: sudo /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
