tasks:
  - name: Backend Service
    openMode: split-left
    init: |
      sudo apt update
      sudo apt install python3 python3-venv -y
      python3 -m venv venv
      ./venv/bin/pip install -r backend/requirements.txt
    command: ./venv/bin/python backend/app/main.py

  - name: Frontend Service
    openMode: split-right
    init: cd frontend && npm install
    command: cd frontend && npm run dev

  - name: Grafana
    openMode: tab-after
    init: |
      wget https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb
      sudo dpkg -i grafana_10.2.3_amd64.deb
      sudo systemctl enable grafana-server
    command: sudo systemctl start grafana-server

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
