tasks:
  - name: Backend Service
    openMode: split-left
    init: |
      sudo apt update
      sudo apt install -y python3 python3-venv python3-pip
      python3 -m venv venv
      source venv/bin/activate
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    command: source venv/bin/activate && cd backend && python -m app.main

  - name: Frontend Service
    openMode: split-right
    init: |
      sudo apt update
      sudo apt install -y curl
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt install -y nodejs
      cd frontend
      npm install
    command: cd frontend && npm run dev

  - name: Grafana
    openMode: tab-after
    init: |
      sudo apt update
      sudo apt install -y libfontconfig1 musl wget
      wget https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb
      sudo dpkg -i grafana_10.2.3_amd64.deb
    command: sudo /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana --packaging=deb

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
