tasks:
  - name: Backend Service
    openMode: split-left
    init: |
      source ./venv/bin/activate
      cd backend
    command: python -m app.main

  - name: Frontend Service
    openMode: split-right
    init: |
      cd frontend
    command: npm run dev

  - name: Grafana
    openMode: tab-after
    init: |
      sudo mkdir -p /var/lib/grafana
    command: sudo /usr/sbin/grafana-server \
      --config=/etc/grafana/grafana.ini \
      --homepath=/usr/share/grafana \
      --packaging=deb

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
