version: "3.9"

services:
  backend:
    build: ./backend/
    container_name: backend_service
    restart: always
    ports:
      - "8005:8005"     # FastAPI expuesto en localhost:8005
    environment:
      - MONGO_URI=mongodb+srv://user_mongo:dobleq3@cluster0.sj5du.mongodb.net/electronica?retryWrites=true&w=majority  # conexión a Mongo Atlas
    volumes:
      - backend_data:/usr/src/app/data   # volumen persistente
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "5173:5173"     # Vite expuesto en localhost:5173
    environment:
      - VITE_API_URL=http://backend:8005   # conexión al backend FastAPI dentro de la red Docker
    depends_on:
      - backend
    networks:
      - app_network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana_service
    restart: always
    ports:
      - "3000:3000"   # Grafana en localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana   # volumen persistente para dashboards y configuración
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:   # volumen persistente para backend
  grafana_data:   # volumen persistente para grafana
