

services:
  backend:
    build: ./backend/
    container_name: backend_service
    restart: always
    ports:
      - "8005:8005"  # FastAPI expuesto en localhost:8005
    environment:
      MONGO_URI: mongodb+srv://user_mongo:dobleq3@cluster0.sj5du.mongodb.net/electronica?retryWrites=true&w=majority  # conexión a Mongo Atlas desde .env
    volumes:
      - backend_data:/usr/src/app/data
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "5173:5173"  # Vite expuesto en localhost:5173
    depends_on:
      - backend
    networks:
      - app_network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana_service
    restart: always
    ports:
      - "3000:3000"  # Grafana en localhost:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - grafana
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  backend_data:
  grafana_data:
