tasks:
  backend:
      name: Backend Service
      command: |
        until sudo apt-get update; do
          echo "Esperando que apt se libere..."
          sleep 2
        done
        sudo apt-get install -y python3 python3-venv python3-pip
        python3 -m venv venv
        source venv/bin/activate
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m app.main
      triggeredBy:
        - manual

  frontend:
    name: Frontend Service
    command: |
      wait_for_apt() {
        while sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
              sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
              sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Esperando que apt se libere..."
          sleep 2
        done
      }

      wait_for_apt
      sudo apt-get update

      wait_for_apt
      sudo apt-get install -y curl

      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

      wait_for_apt
      sudo apt-get install -y nodejs

      cd frontend
      npm install
      npm run dev
    triggeredBy:
      - manual

  grafana:
      name: Grafana
      command: |
        while sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
              sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
              sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Esperando que apt se libere..."
          sleep 2
        done
        sudo apt update
        sudo apt install -y libfontconfig1 musl wget
        wget https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb
        sudo dpkg -i grafana_10.2.3_amd64.deb
        sudo /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana --packaging=deb
      triggeredBy:
        - manual
        
  hello:
    name: Hello World
    command: |
      echo "Hello, World!"
    triggeredBy:
      - manual

services:
  backend-check:
    name: Backend Readiness Check
    description: Verifica si el backend está activo
    commands:
      start: |
        echo "Iniciando verificación de backend..."
        touch /tmp/backend.started
        while true; do
          sleep 1
          date
        done
      ready: |
        if [ -f /tmp/backend.started ]; then
          echo "Backend service is ready"
          exit 0
        else
          echo "Backend service is not ready"
          exit 1
        fi
    triggeredBy:
      - postEnvironmentStart
